name = "Bora"
uuid = "f2bc0970-dd97-4292-b510-1db90d18516e"
authors = ["marcobonici <bonici.marco@gmail.com>"]
version = "0.3.0"

[deps]
AbstractCosmologicalEmulators = "c83c1981-e5c4-4837-9eb8-c9b1572acfc6"

[compat]
AbstractCosmologicalEmulators = "0.3.1"