name = "Bora"
uuid = "f2bc0970-dd97-4292-b510-1db90d18516e"
authors = ["marcobonici <bonici.marco@gmail.com>"]
version = "0.1.0"

[deps]
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
SimpleChains = "de6bee2f-e2f4-4ec7-b6ed-219cc6f6e9e5"
